### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/hyperseti#1]
put your feature requests here!

**Comment by texadactyl** [comment]
* Convert this into an installable package - setup.py etc.

**Comment by luigifcruz** [comment]
- Include automated testing and packaging. The Github Actions workflows from `turboSETI` should work on this project without major changes. I can port them if this suggestion is accepted.

**Comment by telegraphic** [comment]
definitely accepted!

**Comment by texadactyl** [comment]
Create an Anaconda package for hyperseti so that the need for mixing conda and pip (petrol and water) need not occur any more.

**Comment by texadactyl** [comment]
Remove all dependencies on blimpy.

**Comment by texadactyl** [comment]
Finish migration from logging to logbook.

**Comment by luigifcruz** [comment]
> definitely accepted!

Done! PR #30

**Comment by texadactyl** [comment]
Frequency masking as in https://github.com/UCBerkeleySETI/turbo_seti/issues/125

**Comment by texadactyl** [comment]
Remove all dependencies on blimpy and setigen as they do not support polarisation.

**Comment by texadactyl** [comment]
Add a feature similar to ```turboseti_stream``` i.e. permit the instantiation and invocation of searches without having to create an input Filterbank file or HDF5 file.

**Comment by telegraphic** [comment]
A lot has changed, closing this
