### ISSUE TITLE
TODO: Speed up hitsearch

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/hyperseti#2]

**Comment by telegraphic** [comment]
From slack chat with @FX196 : 
Profiling and found that the for loop takes up less than 1% of the processing time:facepalm:

Most of the time is spent in this block: https://github.com/mritools/cupyimg/blob/master/cupyimg/skimage/feature/peak.py#L383 

Which takes up 50-96% of the time.
And the block at line 395 sometimes takes the other 50% when the one at 383 doesn't take up almost all the time
The 383 block is mostly just finding the maximum values along two axes of the image, and I don't see much space to optimize it

The second block at line 395 calls into measure.regionprops, which is also mostly cupy calls

The largest area for optimization I see seems to be here: https://github.com/mritools/cupyimg/blob/master/cupyimg/skimage/measure/_regionprops.py#L1230

`ndimage.find_objects` isn't implemented on the GPU yet so they're using the CPU version.

Actually `measure.regionprops` does seem to take up most of the time when I call test_hyperseti.test_hitsearch_multi()

The block takes up 0.018 ish out of 0.022 ish total processing time
And at extreme cases in `test_hyperseti.test_hitsearch()` it can take 0.488 out of 0.758 total

**Comment by telegraphic** [comment]
@wfarah the matrix (N_drift, N_channels), where N_drift is the number of drift trials (probably 100-1000 trials for most use cases), and N_channels is how many channels you read in. A 'coarse channel' from GBT is about 1 million, so let's say 10^5 to 10^7 channels.

Also looping in @lacker who also expressed interest in helping out on hyperseti.  To recap, the slowest part of the code seems to be `_prominent_peaks` method in cupyimg:
https://github.com/mritools/cupyimg/blob/master/cupyimg/skimage/feature/peak.py#L348

**Comment by telegraphic** [comment]
@FX196 identified this block as being slow:
```python
    ycoords_size = 2 * min_ydistance + 1
    xcoords_size = 2 * min_xdistance + 1
    img_max = ndi.maximum_filter1d(
        img, size=ycoords_size, axis=0, mode="constant", cval=0
    )
    img_max = ndi.maximum_filter1d(
        img_max, size=xcoords_size, axis=1, mode="constant", cval=0
    )
    mask = img == img_max
    img *= mask
    img_t = img > threshold
 ```

So likely the culprit is `ndi.maximum_filter1d`.

**Comment by telegraphic** [comment]
Hmm, in my profiling I'm seeing  `props = measure.regionprops(label_img, img_max)` call as the slow point, and it looks like this isn't yet implemented on the gpu:
https://github.com/mritools/cupyimg/blob/52c9abcb6b1978449ef0a8bb3c774a4bcb66ab07/cupyimg/skimage/measure/_regionprops.py#L942

**Comment by telegraphic** [comment]
Looks to me this is much faster:
```python
    # Find array (x,y) indexes corresponding to max pixels
    peak_idxs = cp.argwhere(img_t)
    # Find corresponding maximum values
    peak_vals = img[peak_idxs[:, 0], peak_idxs[:, 1]]
    # Sort peak values low to high
    val_sort_idx = cp.argsort(peak_vals)[::-1]
    # Return (x,y) coordinates corresponding to sorted max pixels
    coords = peak_idxs[val_sort_idx]
```

than [existing lines 395-400](https://github.com/mritools/cupyimg/blob/52c9abcb6b1978449ef0a8bb3c774a4bcb66ab07/cupyimg/skimage/feature/peak.py#L395):

```python
    label_img = measure.label(img_t)
    props = measure.regionprops(label_img, img_max)
    # Sort the list of peaks by intensity, not left-right, so larger peaks
    # in Hough space cannot be arbitrarily suppressed by smaller neighbors
    props = sorted(props, key=lambda x: x.max_intensity)[::-1]
    coords = cp.asarray([np.round(p.centroid) for p in props], dtype=int)
```

**Comment by telegraphic** [comment]
aaand this is sometimes very slow:

https://github.com/mritools/cupyimg/blob/52c9abcb6b1978449ef0a8bb3c774a4bcb66ab07/cupyimg/skimage/feature/peak.py#L411

Presumably when it finds a large number of hits? (Todo: investigate)

**Comment by telegraphic** [comment]
Added upstream issue to check my speedup makes sense: https://github.com/mritools/cupyimg/issues/19

**Comment by lacker** [comment]
I tested this out a bit, I also get that almost all time is spent in `_prominent_peaks` and GPU usage is pretty low so it's all dominated by this method not using the GPU. Do you specifically want the peak prioritization method that `_prominent_peaks` does, or would it be okay to use `peak_local_max`? `peak_local_max` is actually exported by skimage, and it seems simpler. It doesn't support a separate min-distance in the different dimensions but the algorithm itself isn't too complicated ( https://github.com/scikit-image/scikit-image/blob/fa71d1a1600faf93f9fd9200e2c58c307a5c9bb6/skimage/feature/peak.py#L114 ) and it seems like it should be possible to make it GPU-bound. Basically just saying a "peak" is any pixel above a threshold that is also the maximum of some local rectangle.

**Comment by telegraphic** [comment]
@lacker I discounted this method earlier as I wanted different values for `min_distance` along x (frequency) and y (drift trial) axes. But I'm not actually sure that we do need to be able to do that -- if it's much faster that might be a good reason to switch.

I should say two things: 1) I'm not really sure what the difference is between peak_local_max and prominent_peak algorithms, and b) I'm not 100% sure the 'best' way to find peaks in the doppler-frequency space. We ideally want to be able to find faint signals co-incident with strong RFI sources, but RFI can have complex structure and it's difficult to disentangle what is the 'real' signal and what is RFI. I have an idea that we could use higher-order stats like kurtosis to disentangle constant tones (low kurtosis) from variable RFI (high kurtosis), but this is still in the oven.

**Comment by telegraphic** [comment]
now using argrelmax, closing
