### ISSUE TITLE
Assertion error in test_dedoppler() after introducing 3d in DataArray.data

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/hyperseti#23]
I believe that test_dedoppler worked before.  
Introducing the polarisation (beam) dimension probably caused this.

blimpy.waterfall INFO     Conversion time: 0.00sec
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-texadactyl'
Inserted drift rate:  0.0 Hz / s 	SUM: 2026.93
Recovered drift rate: -0.03125 Hz / s 	SUM: 2026.93

DEBUG maxpixel= 32267
DEBUG mdrift= 31
DEBUG mchan= 523
Traceback (most recent call last):
  File "test_hyperseti.py", line 265, in <module>
    test_dedoppler()
  File "test_hyperseti.py", line 70, in test_dedoppler
    assert np.abs(mchan - 500) <= 1
AssertionError

**Comment by telegraphic** [comment]
I've got a few pressing deadlines this week but will try and fix asap. (This is what I get for demanding polarization support then forgetting to implement it).

**Comment by texadactyl** [comment]
I inserted some tracing into test_dedoppler that might be helpful.
```
blimpy.waterfall INFO     Conversion time: 0.00sec
test_dedoppler TRACE dedopp returned from dedoppler():
 [[31.298088 29.147776 34.73328  ... 40.472702 34.826904 31.429382]
 [26.654598 37.03268  33.08083  ... 32.554005 34.21309  25.926668]
 [31.580868 32.773945 31.87496  ... 33.539455 33.161575 30.003521]
 ...
 [30.13145  27.996962 37.07213  ... 28.67624  34.309555 41.309044]
 [30.399427 34.256107 33.223648 ... 40.005093 38.032906 33.42448 ]
 [31.762932 35.523052 32.0654   ... 35.76001  36.208187 27.134338]]
test_dedoppler TRACE manual_dd_tot: 2029.0631217956543
test_dedoppler TRACE maxpixel: 32267
test_dedoppler TRACE mdrift: 31 , mchan: 523
test_dedoppler TRACE maxpixel_val: 2029.0632
Inserted drift rate:  0.0 Hz / s 	SUM: 2029.06
Recovered drift rate: -0.03125 Hz / s 	SUM: 2029.06
```

**Comment by texadactyl** [comment]
No longer present.
