### ISSUE TITLE
CODE OPTIMIZATION: Use less GPU memory

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/hyperseti#25]
The pipeline seems to be using much more GPU RAM than seems reasonable -- figure out why this is! Am I creating multiple copies of the same array?

**Comment by texadactyl** [comment]
Something to watch as it evolves: cuda + numba, supported by nvidia.
https://developer.nvidia.com/blog/numba-python-cuda-acceleration/

**Comment by telegraphic** [comment]
Stepped plan uses much less memory -- still optimization to do, but can now fit a full 2^20 channels on the GPU no issue.
