### ISSUE TITLE
hyperseti.py:269: KeyError (in hitsearch)

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/hyperseti#32]
t0 = time.time()
        if len(fcoords) > 0:
            driftrate_peaks = drift_trials[dcoords]
>           logger.debug(f"{metadata['f0']}, {metadata['df']}, {fcoords}")
E           KeyError: 'f0'

**Comment by telegraphic** [comment]
yup, sorry I changed the underlying metadata keywords, I'll fix this later this week too

**Comment by texadactyl** [comment]
Metadata suggestions:
* Write up (technote) the intended metadata names and definitions.  Stowe it in the ```docs``` subfolder.  It's a "living" technote.
* Consider making the metadata an object defined by a class with member functions to load/unload as required.

I would have done that for you but I am a crappy mind-reader!  (-:

**Comment by texadactyl** [comment]
No longer present.
