### ISSUE TITLE
Technote images

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/hyperseti#34]
<img width="702" alt="Screen Shot 2021-07-23 at 2 11 16 pm" src="https://user-images.githubusercontent.com/713251/126743653-704983e9-2358-41dc-99cc-5181070413f6.png">

**Comment by telegraphic** [comment]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/713251/126744321-575ecfc6-9f37-4cff-82b1-8e4351c1eaf9.png">

**Comment by telegraphic** [comment]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/713251/126745394-373cf705-ae94-48ca-ae6e-ab17d7d97075.png">

**Comment by texadactyl** [comment]
Like the 3D visualisations!

**Comment by telegraphic** [comment]
It's pretty neat -- modified from dask/xarray. This will show up for anyone using jupyter notebooks

**Comment by telegraphic** [comment]
(btw, this issue is a hacky way to upload images for the main technote)

**Comment by telegraphic** [comment]
![image](https://user-images.githubusercontent.com/713251/227689177-42e81c48-53cc-4eb9-a8f9-4cea8ce37f2e.png)
