### ISSUE TITLE
Need an optional "blank_dc" function

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/hyperseti#52]
Once the huge DC spike in the Voyager .h5 file was avoided, hyperseti behaved a lot better.  See issue #51.

**Comment by texadactyl** [comment]
For the antenna arrays (E.g. MeerKAT), this is probably not necessary.

**Comment by telegraphic** [comment]
Hi @texadactyl, working on hyperseti over my Easter break (just merged in your PR)

**Comment by texadactyl** [comment]
Back to daddy duties with ya ... don't get scolded! 🤠

**Comment by texadactyl** [comment]
@telegraphic 
Saw: "DC bin needs to be blanked. This is now done with sk_flag".  But, I thought that "SK" referred to special kurtosis.  How does that fulfill the smoothing of the coarse channel for those situations where it is needed?

**Comment by telegraphic** [comment]
between SK flagging and blank_extrema functions, DC bin is no longer an issue when calculating SNR and mean for normalization. As such special treatment of center channel is not required.
