### ISSUE TITLE
Remove dependency on cusignal

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/hyperseti#71]
Currently cusignal is needed for `argrelmax`. cusignal is a pain to install and incompatible with `pip`, you need to use `conda`.

cusignal also does some weird precompile at installation time, so you can't just grab the code from the repo and throw it in to hyperseti codebase.

Best approach will be to carefully write our own peak finding algorithm on the GPU. This is currently the bottleneck of the whole pipeline so most fruitful area to optimize.

**Comment by spoofster123** [comment]
should there be a separate repo for this? 

I wouldn't mind taking a stab at it.

**Comment by telegraphic** [comment]
New peak finding algorithm in #83. Still has some issues though :/
