### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by wfarah** [UCBerkeleySETI/hyperseti#99]
The installation was failing due to this line:

`cupy        = "~11."`

in: https://github.com/UCBerkeleySETI/hyperseti/blob/master/pyproject.toml#L12

I think the parser doesn't like the fact that there is no digit after the decimal point

**Comment by telegraphic** [comment]
Oop, late night change to relax that dependency -- I've just pushed a fix straight to master branch

**Comment by telegraphic** [comment]
Closing, should be fixed. Note you should now be able to install via conda with 

```
 conda install -c technosignatures hyperseti 
```
